version: '3.7'
services:
  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - /home/dratinox/mongodb/database:/data/db
  face_detect_container:
    build: .
    env_file:
      - .env
networks:
  default:
    external:
      name: "face-detect-network"

