export default {
    FACE_API_KEY: process.env.FACE_API_KEY,
    FACE_API_HOST: process.env.FACE_API_HOST,
    FACE_API_PATH_VERIFY: process.env.FACE_API_PATH_VERIFY,
    FACE_API_PATH_DETECT: process.env.FACE_API_PATH_DETECT,
    FACE_API_CONFIDENCE_TRESHOLD: process.env.FACE_API_CONFIDENCE_TRESHOLD,
};
